/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.88
 * Generated at: 2020-09-23 04:52:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

public final class role_002dpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/include-nav.jsp", Long.valueOf(1600830232323L));
    _jspx_dependants.put("/WEB-INF/include-head.jsp", Long.valueOf(1596523469589L));
    _jspx_dependants.put("/WEB-INF/include-sidebar.jsp", Long.valueOf(1596523268932L));
    _jspx_dependants.put("/WEB-INF/modal-role-add.jsp", Long.valueOf(1596450215832L));
    _jspx_dependants.put("/WEB-INF/modal-role-edit.jsp", Long.valueOf(1596071197918L));
    _jspx_dependants.put("/WEB-INF/modal-role-remove.jsp", Long.valueOf(1596198775508L));
    _jspx_dependants.put("/WEB-INF/modal-role-assign-auth.jsp", Long.valueOf(1599981064385L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>尚筹网(゜-゜)</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<base\r\n");
      out.write("\thref=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(':');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverPort }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".tree li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tree-closed {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tree-expanded {\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/docs.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"layer/layer.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"ztree/jquery.ztree.all-3.5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"crowd/include-sidebar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//genereateTree();\r\n");
      out.write("\t\t//genereateTree1();\r\n");
      out.write("\t\t$(\".list-group-item\").click(function() {\r\n");
      out.write("\t\t\tif ($(this).find(\"ul\")) {\r\n");
      out.write("\t\t\t\t$(this).toggleClass(\"tree-closed\");\r\n");
      out.write("\t\t\t\tif ($(this).hasClass(\"tree-closed\")) {\r\n");
      out.write("\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"ul\", this).show(\"fast\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/pagination.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery/jquery.pagination.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"ztree/zTreeStyle.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"ztree/jquery.ztree.all-3.5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"crowd/my-role.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t//1.为分页操作初始化数据\r\n");
      out.write("\t\twindow.pageNum = 1;\r\n");
      out.write("\t\twindow.pageSize = 10;\r\n");
      out.write("\t\twindow.keyword = \"\";\r\n");
      out.write("\t\t//2.调用执行分页的函数，执行分页效果\r\n");
      out.write("\t\tgeneratePage();\r\n");
      out.write("\t\t//3.为搜索按钮绑定单击函数\r\n");
      out.write("\t\t$(\"#searchBtn\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t//1.获取keyword\r\n");
      out.write("\t\t\twindow.keyword = $(\"#keywordInput\").val();\r\n");
      out.write("\t\t\twindow.pageNum = 1;\r\n");
      out.write("\t\t\t//调用分页函数\r\n");
      out.write("\t\t\tgeneratePage();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//打开添加模态框\r\n");
      out.write("\t\t$(\"#addModalBtn\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t//$(\"#addModal\").empty();\r\n");
      out.write("\t\t\t$(\"#addModal\").modal(\"show\");\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//添加新角色\r\n");
      out.write("\t\t$(\"#saveRoleBtn\")\r\n");
      out.write("\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t//获取到input框内的roleName\r\n");
      out.write("\t\t\t\t\t\t\t//#addModal [name = roleName]  表示在addModal模态框下的name=roleName元素\r\n");
      out.write("\t\t\t\t\t\t\t//$.trim,去掉前后空格\r\n");
      out.write("\t\t\t\t\t\t\tvar roleName = $\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.trim($(\"#addModal [name=roleName]\").val());\r\n");
      out.write("\t\t\t\t\t\t\tif (roleName == \"\") {\r\n");
      out.write("\t\t\t\t\t\t\t\tlayer.msg(\"输入角色名称不能为空！\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t//发送ajax请求\r\n");
      out.write("\t\t\t\t\t\t\tif (roleName != \"\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"url\" : \"role/save.json\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"type\" : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"data\" : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"name\" : roleName\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"dataType\" : \"json\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"success\" : function(response) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar result = response.operationResult;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif (result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tlayer.msg(\"操作成功！\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//重新加载分页\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twindow.pageNum = 999999;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tgeneratePage();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif (result == \"FAILED\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tlayer.msg(\"操作失败！\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ response.message);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"error\" : function(response) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlayer.msg(response.status + \"  \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ response.statusText);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#addModal\").modal(\"hide\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t//清理模态框\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#addModal [name = roleName]\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t//重新加载分页\r\n");
      out.write("\t\t\t\t\t\t\t/* window.pageNum = 999999;\r\n");
      out.write("\t\t\t\t\t\t\tgeneratePage(); */\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t//回显信息\r\n");
      out.write("\t\t$(\"#rolePageBody\").on(\"click\", \".pencilBtn\", function() {\r\n");
      out.write("\t\t\t//打开模态框\r\n");
      out.write("\t\t\t$(\"#updateModal\").modal(\"show\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t//获取到角色名称\r\n");
      out.write("\t\t\tvar roleName = $(this).parent().prev().text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t//获取当前角色的id\r\n");
      out.write("\t\t\t//为了让执行更新的按钮能够获取到roleId所以将其设置为全局变量\r\n");
      out.write("\t\t\twindow.roleId = this.id;\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#updateModal [name=roleName]\").val(roleName);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//更新\r\n");
      out.write("\t\t$(\"#updateRoleBtn\").click(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t//取出文本框内的角色信息\r\n");
      out.write("\t\t\t\t\tvar roleName = $(\"#updateModal [name=roleName]\").val();\r\n");
      out.write("\t\t\t\t\tif (roleName == \"\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"输入角色名称不能为空！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif (roleName != \"\") {\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\"url\" : \"role/update.json\",\r\n");
      out.write("\t\t\t\t\t\t\t\"type\" : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\"data\" : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\"id\" : window.roleId,\r\n");
      out.write("\t\t\t\t\t\t\t\t\"name\" : roleName\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\"dataType\" : \"json\",\r\n");
      out.write("\t\t\t\t\t\t\t\"success\" : function(response) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar result = response.operationResult;\r\n");
      out.write("\t\t\t\t\t\t\t\tif (result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlayer.msg(\"操作成功！\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//重新加载分页\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgeneratePage();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#updateModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif (result == \"FAILED\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlayer.msg(\"操作失败！\" + response.message);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\"error\" : function(response) {\r\n");
      out.write("\t\t\t\t\t\t\t\tlayer.msg(response.status + \"  \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ response.statusText);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#updateModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t//打开删除模态框，提示是否确认删除,点击确认进行删除\r\n");
      out.write("\t\t$(\"#removeRoleBtn\").click(function() {\r\n");
      out.write("\t\t\tvar requestBody = JSON.stringify(window.roleIdList);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\"url\" : \"role/delete/by/id/list.json\",\r\n");
      out.write("\t\t\t\t\"type\" : \"post\",\r\n");
      out.write("\t\t\t\t\"data\" : requestBody,\r\n");
      out.write("\t\t\t\t\"contentType\" : \"application/json;charset=UTF-8\",\r\n");
      out.write("\t\t\t\t\"dataType\" : \"json\",\r\n");
      out.write("\t\t\t\t\"success\" : function(response) {\r\n");
      out.write("\t\t\t\t\tvar result = response.operationResult;\r\n");
      out.write("\t\t\t\t\tif (result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"删除成功！\");\r\n");
      out.write("\t\t\t\t\t\t// 重新加载分页\r\n");
      out.write("\t\t\t\t\t\tgeneratePage();\r\n");
      out.write("\t\t\t\t\t\t$(\"#updateModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif (result == \"FAILED\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"删除失败！\" + response.message);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"error\" : function(response) {\r\n");
      out.write("\t\t\t\t\tlayer.msg(response.status + \"  \" + response.statusText);\r\n");
      out.write("\t\t\t\t\t$(\"#updateModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//关闭模态框\r\n");
      out.write("\t\t\t$(\"#deleteModal\").modal(\"hide\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//单条删除\r\n");
      out.write("\t\t$(\"#rolePageBody\").on(\"click\", \".removeBtn\", function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t//获取到角色名称\r\n");
      out.write("\t\t\tvar roleName = $(this).parent().prev().text();\r\n");
      out.write("\t\t\tvar rolelist = [ {\r\n");
      out.write("\t\t\t\troleId : this.id,\r\n");
      out.write("\t\t\t\troleName : roleName\r\n");
      out.write("\t\t\t} ];\r\n");
      out.write("\t\t\tshowDeleteModal(rolelist);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//给总的checkbox绑定单击响应函数\r\n");
      out.write("\t\t$(\"#summaryBox\").click(function() {\r\n");
      out.write("\t\t\t//获取自身选择状态\r\n");
      out.write("\t\t\tvar currentStatus = this.checked;\r\n");
      out.write("\t\t\t//用当前多选框的状态赋值给其他多选框\r\n");
      out.write("\t\t\t$(\".itembox\").prop(\"checked\", currentStatus);\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//反向操作\r\n");
      out.write("\t\t$(\"#rolePageBody\").on(\"click\", \".itembox\", function() {\r\n");
      out.write("\t\t\t//获取选中的全部itembox的数量\r\n");
      out.write("\t\t\tvar checkedBoxCount = $(\".itembox:checked\").length;\r\n");
      out.write("\t\t\t//获取itemBox的全部数量\r\n");
      out.write("\t\t\tvar totalBoxCount = $(\".itembox\").length;\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#summaryBox\").prop(\"checked\", checkedBoxCount == totalBoxCount);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//给批量删除按钮绑定单击响应函数\r\n");
      out.write("\t\t$(\"#deleteRoleBtn\").click(function() {\r\n");
      out.write("\t\t\t//创建数组用来存放role对象\r\n");
      out.write("\t\t\tvar rolelist = [];\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\".itembox:checked\").each(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar roleId = this.id;\r\n");
      out.write("\t\t\t\tvar roleName = $(this).parent().next().text();\r\n");
      out.write("\t\t\t\trolelist.push({\r\n");
      out.write("\t\t\t\t\troleId : this.id,\r\n");
      out.write("\t\t\t\t\troleName : roleName\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (rolelist.length == 0) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlayer.msg(\"请至少选择一个角色名称再进行操作！\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tshowDeleteModal(rolelist);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//给分配权限按钮绑定单级响应函数打开模态框\r\n");
      out.write("\t\t$(\"#rolePageBody\").on(\"click\", \".checkBtn\", function() {\r\n");
      out.write("\t\t\t//alert(\"111\");\r\n");
      out.write("\t\t\t//把当前角色的id存入全局变量\r\n");
      out.write("\t\t\twindow.roleId = this.id;\r\n");
      out.write("\t\t\t//打开模态框\r\n");
      out.write("\t\t\t$(\"#assignModal\").modal(\"show\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tfillAuthTree();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#assignBtn\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t//1.收集树形结构中被勾选的节点\r\n");
      out.write("\t\t\t//声明一个专用数组来保存被勾选的id\r\n");
      out.write("\t\t\tvar authIdArray = [];\r\n");
      out.write("\t\t\t//2.获取zTreeObj对象\r\n");
      out.write("\t\t\tvar zTreeObj = $.fn.zTree.getZTreeObj(\"authTreeDemo\");\r\n");
      out.write("\t\t\t//3.获取全部勾选的节点\r\n");
      out.write("\t\t\tvar checkedNodes = zTreeObj.getCheckedNodes();\r\n");
      out.write("\t\t\t//4遍历数组\r\n");
      out.write("\t\t\tfor (var i = 0; i < checkedNodes.length; i++) {\r\n");
      out.write("\t\t\t\tvar checkedNode = checkedNodes[i];\r\n");
      out.write("\t\t\t\tvar authId = checkedNode.id;\r\n");
      out.write("\t\t\t\tauthIdArray.push(authId);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//alert(authIdArray);\r\n");
      out.write("\t\t\tvar requestBoby = {\r\n");
      out.write("\t\t\t\t\"authIdArray\" : authIdArray,\r\n");
      out.write("\t\t\t\t//为了方便服务器端handler方法能够统一使用List<Integer>方式接收数据，roleId也存入数组内\r\n");
      out.write("\t\t\t\t\"roleId\" : [ window.roleId ]\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\trequestBoby = JSON.stringify(requestBoby);\r\n");
      out.write("\t\t\talert(requestBoby);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\"url\" : \"assign/do/role/assign/auth.json\",\r\n");
      out.write("\t\t\t\t\"type\" : \"post\",\r\n");
      out.write("\t\t\t\t\"data\" : requestBoby,\r\n");
      out.write("\t\t\t\t\"contentType\" : \"application/json;charset=UTF-8\",\r\n");
      out.write("\t\t\t\t\"dataType\" : \"json\",\r\n");
      out.write("\t\t\t\t\"success\" : function(response) {\r\n");
      out.write("\t\t\t\t\tvar result = response.operationResult;\r\n");
      out.write("\t\t\t\t\tif (result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"操作成功！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif (result == \"FAILED\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"操作失败！\"+response.message);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"error\" : function(response) {\r\n");
      out.write("\t\t\t\t\tlayer.msg(response.status + \"  \" + response.statusText);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#assignModal\").modal(\"hide\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    <!-- 引入security标签 -->\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" style=\"font-size: 32px;\" href=\"#\">众筹平台\r\n");
      out.write("\t\t\t\t\t\t- 控制面板</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li style=\"padding-top: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-default btn-success dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_security_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t个人设置</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t消息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"security/do/logout.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li style=\"margin-left: 10px; padding-top: 8px;\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<form class=\"navbar-form navbar-right\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"查询\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t<div class=\"tree\">\r\n");
      out.write("\t\t<ul style=\"padding-left: 0px;\" class=\"list-group\">\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><a href=\"admin/to/main/page.html\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-dashboard\"></i> 控制面板</a></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon glyphicon-tasks\"></i> 权限管理 <span\r\n");
      out.write("\t\t\t\t\tclass=\"badge\" style=\"float: right\">3</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"admin/get/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i> 用户维护</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"role/to/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-king\"></i> 角色维护</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"menu/to/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\"></i> 菜单维护</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-ok\"></i> 业务审核 <span class=\"badge\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float: right\">3</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_cert.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 实名认证审核</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_adv.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 广告审核</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_project.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 项目审核</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-th-large\"></i> 业务管理 <span class=\"badge\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float: right\">7</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"cert.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-picture\"></i> 资质维护</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"type.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> 分类管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"process.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-random\"></i> 流程管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"advertisement.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-hdd\"></i> 广告管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"message.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-comment\"></i> 消息模板</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"project_type.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list\"></i> 项目分类</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"tag.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-tags\"></i> 项目标签</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><a href=\"param.html\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\"></i> 参数管理</a></li> \r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-th\"></i> 数据列表\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" class=\"form-inline\" role=\"form\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group has-feedback\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-addon\">查询条件</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"keywordInput\" class=\"form-control has-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" placeholder=\"请输入查询条件\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"searchBtn\" type=\"button\" class=\"btn btn-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-search\"></i> 查询\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"deleteRoleBtn\" type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right; margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\" glyphicon glyphicon-remove\"></i> 删除\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"addModalBtn\" type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-plus\"></i> 新增\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<hr style=\"clear: both;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table  table-bordered\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"30\">#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"30\"><input id=\"summaryBox\" type=\"checkbox\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>名称</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th width=\"100\">操作</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody id=\"rolePageBody\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"Pagination\" class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- 这里显示分页 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"deleteModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">尚筹网系统弹框</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t<h4>请确定是否删除下列角色名称：</h4>\r\n");
      out.write("\t\t\t<div id=\"roleNameDiv\" style=\"text-align: center;\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button id=\"closeRoleBtn\" type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t<button id=\"removeRoleBtn\" type=\"button\" class=\"btn btn-primary\">确认删除</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"addModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">尚筹网系统弹框</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-signin\" role=\"form\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group has-success has-feedback\">\r\n");
      out.write("\t\t\t\t\t\t<input \r\n");
      out.write("\t\t\t\t\t\t\tname=\"roleName\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"请输入角色名称\"\r\n");
      out.write("\t\t\t\t\t\t\tautofocus>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button id=\"closeRoleBtn\" type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t<button id=\"saveRoleBtn\" type=\"button\" class=\"btn btn-primary\">保存</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"updateModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">尚筹网系统弹框</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<form class=\"form-signin\" role=\"form\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group has-success has-feedback\">\r\n");
      out.write("\t\t\t\t\t\t<input \r\n");
      out.write("\t\t\t\t\t\t\tname=\"roleName\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"请输入角色名称\"\r\n");
      out.write("\t\t\t\t\t\t\tautofocus>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button id=\"closeRoleBtn\" type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t<button id=\"updateRoleBtn\" type=\"button\" class=\"btn btn-success\">更新</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<div id=\"assignModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">尚筹网系统弹窗</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"authTreeDemo\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"assignBtn\" type=\"button\" class=\"btn btn-primary\">好的，我设置好了！执行保存。</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_security_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_security_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_security_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005fauthentication_005f0.setParent(null);
      // /WEB-INF/include-nav.jsp(22,8) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005fauthentication_005f0.setProperty("principal.originalAdmin.userName");
      int _jspx_eval_security_005fauthentication_005f0 = _jspx_th_security_005fauthentication_005f0.doStartTag();
      if (_jspx_th_security_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f0);
      _jspx_th_security_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_security_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_security_005fauthentication_005f0_reused);
    }
    return false;
  }
}
