server:
  port: 3000

spring:
  redis:
    host: 192.168.0.88
  application:
    name: atguigu-crowd-redis
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
      
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
      