/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.88
 * Generated at: 2020-07-17 01:03:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<base\r\n");
      out.write("\thref=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(':');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverPort }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"layer/layer.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar student = {\r\n");
      out.write("\t\t\t\"id\" : \"01\",\r\n");
      out.write("\t\t\t\"sname\" : \"王五\",\r\n");
      out.write("\t\t\t\"address\" : {\r\n");
      out.write("\t\t\t\t\"province\" : \"黑龙江\",\r\n");
      out.write("\t\t\t\t\"city\" : \"哈尔滨市\",\r\n");
      out.write("\t\t\t\t\"street\" : \"中央大街\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"subject\" : [ {\r\n");
      out.write("\t\t\t\t\"subjectName\" : \"JAVA\",\r\n");
      out.write("\t\t\t\t\"subjectChengji\" : 100\r\n");
      out.write("\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t\"subjectName\" : \"WEB\",\r\n");
      out.write("\t\t\t\t\"subjectChengji\" : 100\r\n");
      out.write("\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\t\"subjectName\" : \"PYTHON\",\r\n");
      out.write("\t\t\t\t\"subjectChengji\" : 100\r\n");
      out.write("\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t],\r\n");
      out.write("\t\t\t\"map\" : {\r\n");
      out.write("\t\t\t\t\"k1\" : \"v1\",\r\n");
      out.write("\t\t\t\t\"k2\" : \"v2\",\r\n");
      out.write("\t\t\t\t\"k3\" : \"v3\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar requestBoby = JSON.stringify(student);\r\n");
      out.write("\t\t$(\"#btn02\").click(function() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\"url\" : \"send/student.json\",\r\n");
      out.write("\t\t\t\t\"type\" : \"post\",\r\n");
      out.write("\t\t\t\t\"data\" : requestBoby,\r\n");
      out.write("\t\t\t\t\"contentType\" : \"application/json;charset=UTF-8\",\r\n");
      out.write("\t\t\t\t\"dataType\" : \"json\",\r\n");
      out.write("\t\t\t\t\"success\" : function(response) {\r\n");
      out.write("\t\t\t\t\tconsole.log(response);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"error\" : function(response) {\r\n");
      out.write("\t\t\t\t\tconsole.log(response);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#btn01\").click(function() {\r\n");
      out.write("\t\t\tvar array = [ 5, 12, 8 ];\r\n");
      out.write("\t\t\tvar requestBoby = JSON.stringify(array);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\"url\" : \"send/array.html\",\r\n");
      out.write("\t\t\t\t\"type\" : \"post\",\r\n");
      out.write("\t\t\t\t\"data\" : requestBoby,\r\n");
      out.write("\t\t\t\t\"contentType\" : \"application/json;charset=UTF-8\",\r\n");
      out.write("\t\t\t\t\"dataType\" : \"text\",\r\n");
      out.write("\t\t\t\t\"success\" : function(response) {\r\n");
      out.write("\t\t\t\t\talert(response);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"error\" : function(response) {\r\n");
      out.write("\t\t\t\t\talert(response);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#btn03\").click(function() {\r\n");
      out.write("\t\t\tlayer.msg(\"layer提示框\");\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<a href=\"test/ssm.html\">SSM环境整合测试</a>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<button id=\"btn01\">Json按钮</button>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<button id=\"btn02\">Student测试Json</button>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<button id=\"btn03\">点我弹框</button>\r\n");
      out.write("\t<br />\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
